# Charting them coronaviruses
> just answering for my own benefit some of the corona questions I had.

- toc: true
- badges: true
- comments: true
- author: Khalid Omar
- categories: [python]
- permalink: /covid19/
- hide: true
- comments: true

In [3]:
#hide
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import altair as alt

# in progress, go back!

## Data

Loading data from [the john hopkins data repo], specifically the [time series data](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series).

- Deaths
- Recovered
- Confirmed

In [56]:
#collapse
def get_timeseries_data():
    """Downloads the three kinds of timeseries data
    and returns a dict with three dataframes"""

    data = {}
    data_files = ["Confirmed", "Deaths", "Recovered"]
    baseurl = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-"

    for name in data_files:
        url = f"{baseurl}{name}.csv"
        df = pd.read_csv(url)
        print(f"Downloaded: {name} with shape {df.shape}")

        df["type"] = name.lower() # type of case
        data[name] = df

    return data

data = get_timeseries_data()

Downloaded: Confirmed with shape (501, 66)
Downloaded: Deaths with shape (501, 66)
Downloaded: Recovered with shape (501, 66)

In [52]:
col_map = {'Province/State': 'state', 'Country/Region': 'country'}
df.rename(columns=col_map, inplace=True)

In [63]:
# convert date columns into one date col with values
def process_timeseries(df):
    col_map = {'Province/State': 'state', 'Country/Region': 'country'}
    df.rename(columns=col_map, inplace=True)
    
    name_cols = list(df.columns[:4]) + ["type"] 
    df = pd.melt(df, name_cols, var_name="Date", value_name="cases")
    
    df["date"] = pd.to_datetime(df.Date) # datetime format
    
    return df

d = process_timeseries(data["Deaths"].copy())
print(d.columns)
d.head()
#d.groupby(["country", "type", "date"]).sum()

Index(['state', 'country', 'Lat', 'Long', 'type', 'Date', 'cases', 'date'], dtype='object')

  state    country      Lat      Long    type     Date  cases       date
0   NaN   Thailand  15.0000  101.0000  deaths  1/22/20    0.0 2020-01-22
1   NaN      Japan  36.0000  138.0000  deaths  1/22/20    0.0 2020-01-22
2   NaN  Singapore   1.2833  103.8333  deaths  1/22/20    0.0 2020-01-22
3   NaN      Nepal  28.1667   84.2500  deaths  1/22/20    0.0 2020-01-22
4   NaN   Malaysia   2.5000  112.5000  deaths  1/22/20    0.0 2020-01-22

In [58]:
#collapse
# now to process the data
for name, df in data.items():
    print(f"{name}: {df.shape}")

Confirmed: (501, 67)
Deaths: (501, 67)
Recovered: (501, 67)

In [36]:
df.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,type
0,NaN,Thailand,15.0000,101.0000,0,0,0,0,2,2,...,35,35,35,41,42,42,42,42,44,recovered
1,NaN,Japan,36.0000,138.0000,0,0,0,0,1,1,...,118,118,144,144,144,150,191,232,235,recovered
2,NaN,Singapore,1.2833,103.8333,0,0,0,0,0,0,...,105,105,109,114,114,114,124,140,144,recovered
3,NaN,Nepal,28.1667,84.2500,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,recovered
4,NaN,Malaysia,2.5000,112.5000,0,0,0,0,0,0,...,35,42,42,49,60,75,87,114,139,recovered

## New markdown cell